coverage:
  status:
    project:
      default:
        target: 80
        threshold: 10
    patch:
      default:
        target: 80
        threshold: 10

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 80
        threshold: 10
      - type: patch
        target: 80
        threshold: 10

flags:
  astro-mermaid:
    paths:
      - "./packages/astro-mermaid/**/*"
    carryforward: true
  astro-reading-time:
    paths:
      - "./packages/astro-reading-time/**/*"
    carryforward: true
  remark-anchor-link:
    paths:
      - "./packages/remark-anchor-link/**/*"
    carryforward: true
  mogeko-typography:
    paths:
      - "./packages/typography/**/*"
    carryforward: true
  mogeko-utils:
    paths:
      - "./packages/utils/**/*"
    carryforward: true
