pull_request_rules:
  - name: Automatic merge from dependabot
    conditions:
      - "author=dependabot[bot]"
      - "label=dependencies"
      - "check-success=Vercel Preview Comments"
      - "check-success=Build the Packages"
      - "check-success=Test Monorepo Packages"
    actions:
      merge:
