pull_request_rules:
  - name: Automatic merge when release new versions
    conditions:
      - "title=chore(release): version packages"
      - "commits=chore(release): version packages"
      - "author=github-actions[bot]"
      - "check-success=Vercel Preview Comments"
      - "files~=CHANGELOG.md"
      - "head~=changeset-release"
    actions:
      merge:
