queue_rules:
  - name: dependabot
    queue_conditions:
      - "check-success=Vercel Preview Comments"
      - "check-success=Build the Packages"
      - "check-success=Test Monorepo Packages"
    batch_size: 10
    batch_max_wait_time: 5min

pull_request_rules:
  - name: Automatic merge when release new versions
    conditions:
      - "title=chore(release): version packages"
      - "commits=chore(release): version packages"
      - "author=github-actions[bot]"
      - "files~=CHANGELOG.md"
      - "head~=changeset-release"
    actions:
      merge:
  - name: Automatic merge from dependabot
    conditions:
      - "author=dependabot[bot]"
      - "label=dependencies"
      - "check-success=Vercel Preview Comments"
      - "check-success=Build the Packages"
      - "check-success=Test Monorepo Packages"
    actions:
      queue:
        name: dependabot
  - name: Automatic label for blog updates
    conditions:
      - "files~=^apps/blog/"
    actions:
      label:
        add: ["app:blog"]
