packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^25.0.2
  playwright: ^1.57.0

catalogs:
  biome:
    '@biomejs/biome': ^2.3.9
  vitest:
    '@vitest/browser-playwright': ^4.0.15
    '@vitest/coverage-v8': ^4.0.15
    vitest: ^4.0.15

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
