packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.1
  playwright: ^1.57.0

catalogs:
  biome:
    '@biomejs/biome': ^2.3.8
  vitest:
    '@vitest/browser-playwright': ^4.0.14
    '@vitest/coverage-v8': ^4.0.14
    vitest: ^4.0.14

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
