import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inconsolata, Noto_Sans_SC } from "next/font/google";

import "@/styles/globals.css";

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  variable: "--font-noto-sans-sc",
});

const inconsolata = Inconsolata({
  subsets: ["latin"],
  fallback: ["ui-monospace", "monospace"],
  variable: "--font-inconsolata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(notoSansSC.variable, inconsolata.variable)}>
        {children}
      </body>
    </html>
  );
}
