import type { Metadata } from "next";
import Head from "next/head";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <link
          rel="preload"
          href="/fonts/NotoSansMonoCJKsc-VF.woff2"
          as="font"
          type="font/woff2"
        />
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
