name: Build

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build the Packages
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.2.0
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: package.json
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build -F "./packages/*"
