name: Monorepo Test

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Test Monorepo Packages
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: actions/cache@v4.0.2
        with:
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-ms-playwright-
          path: /home/runner/.cache/ms-playwright
      - run: pnpm install -rw --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run cov
