name: Monorepo Build

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Monorepo Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"
      - name: Cache Turborepo Tasks
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-turbo-
      - run: pnpm install -rw --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
