name: Monorepo Build

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  preview:
    name: Build and Deploy to Vercel Preview
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.DEPLOYMENT_URL }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ github.actor }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
          cache: "pnpm"
      - uses: actions/cache@v4.0.2
        with:
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-ms-playwright-
          path: /home/runner/.cache/ms-playwright
      - run: pnpm install --global vercel@latest
      - run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
      - run: echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> "$GITHUB_OUTPUT"
        id: deployment
